/* 

ESTARIA GENIAL HACER EL EQ LOGARITMICO // MAS FALSO QUE YO QUE SE PERO PARECE LOGARITMICO
HE QUITADO LA CAPA ALPHA DE if(type==1){  colorMode(HSB);  fill(colorVal, 255,255);  stroke(colorVal, 255,255); colorMode(RGB); }
SE PODRIA PONER

SELECTOR DE ARCHIVO


*/